### ISSUE TITLE
Error during compiling with MQTT support

### ISSUE THREAD

**Issue by katodo** [tzapu/SonoffBoilerplate#11]
Without MQTT support enabled build procedure work well but if I install PubSubClient V 2.6 and enable MQTT support I've this error, can you help me?
 

`SonoffBoilerplate.ino:299: error: 'MQTT' does not name a type
 void mqttCallback(const MQTT::Publish& pub) {

SonoffBoilerplate.ino:299: error: expected unqualified-id before '&' token
 void mqttCallback(const MQTT::Publish& pub) {

SonoffBoilerplate.ino:299: error: expected ')' before '&' token
SonoffBoilerplate.ino:299: error: expected initializer before 'pub'
 void mqttCallback(const MQTT::Publish& pub) {

 D:\Dropbox\Project_Arduino\SonoffBoilerplate_original\SonoffBoilerplate.ino\SonoffBoilerplate.ino.ino: In function 'void updateMQTT(int)':

SonoffBoilerplate.ino:161: error: no matching function for call to 'PubSubClient::publish(char [50], String&)'
   mqttClient.publish(topic, stateString);`

**Comment by tzapu** [comment]
hi,

might be the wrong pbsub try the one annotated in code
https://github.com/Imroy/pubsubclient <https://github.com/Imroy/pubsubclient>

cheers

**Comment by katodo** [comment]
Ok, tnx! I've solved using suggested lib.
During my first test I've used library available from Arduino Lib Manager... but it's a different lib with the same name :)
