### ISSUE TITLE
Feature request: Connect to Blynk after power interruption

### ISSUE THREAD

**Issue by terrag42** [tzapu/SonoffBoilerplate#3]
For the last few weeks I've been testing a single Sonoff running my version of the SonoffBoilerplate which handles eight relays in total. I had a brief power outage at my house yesterday. Afterward, I noticed that the Sonoff was in AP mode. Here's what I think happened: when power returned, the Sonoff tried to connect to my wifi, but the router takes some seconds to boot up. The Sonoff wasn't able to connect so it entered AP mode. The solution was to either do a medium press on the Sonoff button (meduim press = reset the ESP8266) or unplug it and plug it back in. After a reset, it had no trouble connecting to Blynk. If I had a bunch of Sonoffs all around the house, it would be a pain to go around doing medium presses on each one after a power outage. Is there a way to set a timer while in AP mode (maybe after 10 minutes, perhaps?) that tells the ESP to check and see if it can connect to the previously stored WiFi credentials?

**Comment by tzapu** [comment]
hi, 
added wifiManager.setConfigPortalTimeout(180); which basically causes the module to restart if it s not configured in 3 minutes. 

so the flow is: no router, wait 3 mins in config mode, start from beginning if not configured.

hope this helps
