### ISSUE TITLE
No network connection after following all steps

### ISSUE THREAD

**Issue by Dondoozat** [tzapu/SonoffBoilerplate#5]
Hi, 
just found your work on boilerplate for sonoff.
Got a sonoff basic R2 and followed all the instructions, compiling and televersing went fine, achieved to connect on wifimanager then. 
(Sonoff with fast green led blinking)
Then with all the infos needed ( SSID, password, Blynk token) and save done, the sonoff was slowly blynking and nothing more. impossible to make it connect to my wifi network. (and i'm sure about SSID and password, no mistake about it.)
If you have any idea of what I am missing.
Thnaks by advance and for all this suff :)

**Comment by Dondoozat** [comment]
It seems I owned sonoff basic r2 with « sonoff rf r2 v1 0 » labelled on it with big black wires instead of soldered paths beneath. Dunno if it makes a difference

**Comment by tzapu** [comment]
sorry i can't help, been out of this game for a while :|

**Comment by poszu** [comment]
I get:
>ISR not in IRAM!
> User exception ...

most likely on attaching interrupt.  Any clues how to solve it?
