### ISSUE TITLE
Saving parameters

### ISSUE THREAD

**Issue by Michelvl92** [tzapu/SonoffBoilerplate#6]
Hi,

what is the difference between the implementation of saving data like the mqtt or blynk settings in this template, and your other template: https://github.com/tzapu/WiFiManager/tree/master/examples/AutoConnectWithFSParameters

Michel

**Comment by tzapu** [comment]
hi, this just doesn't use the FS module but EEPROM.
Equivalent ways of doing it, EEPROM is simpler, FS may be safer if it has any kind of wear levelling.

Cheers
