### ISSUE TITLE
'MQTT' does not name a type

### ISSUE THREAD

**Issue by sticks221** [tzapu/SonoffBoilerplate#8]
Hi,

Thank you for sharing this project - it looks to be exactly what I need however,  when trying to compile, I get "exit status 1" and the above error with line 299 highlighted.  Please firgive me if this is a silly question but I am new to this - I have double checked that the dependancies are present (esp8266:v2.3.0, BLYNK:v.04.5 and WiFiManager:v0.12.0).

From what I can work out, MQTT is provided by "PubSubClient" which I have checked is also installed (v2.6.0) but I just cant work whats wrong.

Please can you advise?

**Comment by tzapu** [comment]
hmm, maybe it s a different pub sub library?

i am using the form made by lmroy, and the version seems to be 1.99.1.

good luck and thanks

**Comment by sticks221** [comment]
Thanks for the prompt reply,  would you be able you share the library you are using (or a link to it) please?  Google keeps taking me back to the same library that I have installed already.  I have downgraded to v2.2.0 but still no joy.

**Comment by tzapu** [comment]
https://github.com/Imroy/pubsubclient <https://github.com/Imroy/pubsubclient>

try this

cheers

**Comment by sticks221** [comment]
Brilliant - thank you,  thats the one I needed.  I did have to delete the existing one from the IDE first though (My Documents\Arduino\libraries\PubSibClient) in windows.  It seems that this library is newer than the one in the IDE but causes a clash if trying to install on its own.
